import reacttodo from "../images/reacttodo.webp";
import wheather from "../images/wheather.webp";
import facebookclone from "../images/facebookclone.webp";
import portfolio from "../images/portfolio.webp";
import notesapp from "../images/notesapp.webp";
import darkcalculator from "../images/darkcalculator.webp";
import korfez from "../images/korfez.webp";
import urunkatalog from "../images/urunkatalog.webp";
import spendmoneyapp from "../images/spendmoneyapp.webp";
import patikastore from "../images/patikastore.webp";
import stoklistesi from "../images/stoklistesi.webp";
import onlineflightapp from "../images/onlineflightapp.webp";
import memorycardgame from "../images/memorycardgame.webp";
import textgeneratorapp from "../images/textgeneratorapp.webp";
// apk start
import patikastoreapk from "../apks/patikastore.apk";
import stoklistesiapk from "../apks/stoklistesi.apk";

const react_chakra_projects_data = [
  {
    img: textgeneratorapp,
    isMobile: false,
    isResponsive: false,
    title: "Text Generator App",
    html: true,
    css: true,
    bootstrap: false,
    sass: false,
    js: true,
    jqueryy: false,
    jqueryyui: false,
    tailwindd: false,
    react: true,
    reduxx: true,
    chakra: false,
    node: false,
    mongo: false,
    isCodeBtn: {
      isThere: true,
      link: "https://github.com/alperenkursun/text-generator-app",
    },
    isSeeBtn: {
      isThere: true,
      link: "https://aktextgeneratorapp.surge.sh/",
    },
  },
  {
    img: memorycardgame,
    isMobile: false,
    isResponsive: false,
    title: "Memory Card Game",
    html: true,
    css: true,
    bootstrap: false,
    sass: false,
    js: true,
    jqueryy: false,
    jqueryyui: false,
    tailwindd: false,
    react: true,
    reduxx: true,
    chakra: false,
    node: false,
    mongo: false,
    isCodeBtn: {
      isThere: true,
      link: "https://github.com/alperenkursun/memory-card-game",
    },
    isSeeBtn: {
      isThere: true,
      link: "https://memorycardgame01.surge.sh/",
    },
  },
  {
    img: onlineflightapp,
    isMobile: false,
    isResponsive: true,
    title: "Online Flight App",
    html: true,
    css: true,
    bootstrap: false,
    sass: false,
    js: true,
    jqueryy: false,
    jqueryyui: false,
    tailwindd: false,
    react: true,
    reduxx: false,
    chakra: true,
    node: false,
    mongo: false,
    isCodeBtn: {
      isThere: true,
      link: "https://github.com/alperenkursun/online-flight-app",
    },
    isSeeBtn: {
      isThere: true,
      link: "https://onlineflightapp.netlify.app/",
    },
  },
  {
    img: stoklistesi,
    isMobile: true,
    isResponsive: false,
    title: "Stok Listesi Mobil",
    html: false,
    css: false,
    bootstrap: false,
    sass: false,
    js: false,
    jqueryy: false,
    jqueryyui: false,
    tailwindd: false,
    react: true,
    reduxx: false,
    chakra: false,
    node: false,
    mongo: false,
    isCodeBtn: {
      isThere: true,
      link: "https://github.com/alperenkursun/stok-listesi-app",
    },
    isSeeBtn: {
      isThere: true,
      link: stoklistesiapk,
    },
  },
  {
    img: patikastore,
    isMobile: true,
    isResponsive: false,
    title: "Patikastore Mobil",
    html: false,
    css: false,
    bootstrap: false,
    sass: false,
    js: false,
    jqueryy: false,
    jqueryyui: false,
    tailwindd: false,
    react: true,
    reduxx: false,
    chakra: false,
    node: false,
    mongo: false,
    isCodeBtn: {
      isThere: true,
      link: "https://github.com/alperenkursun/patikastore",
    },
    isSeeBtn: {
      isThere: true,
      link: patikastoreapk,
    },
  },
  {
    img: spendmoneyapp,
    isResponsive: false,
    title: "Spend Money App",
    html: true,
    css: true,
    bootstrap: false,
    sass: false,
    js: true,
    jqueryy: false,
    jqueryyui: false,
    tailwindd: true,
    react: true,
    reduxx: true,
    chakra: false,
    node: false,
    mongo: false,
    isCodeBtn: {
      isThere: true,
      link: "https://github.com/alperenkursun/spend-money-app",
    },
    isSeeBtn: {
      isThere: true,
      link: "https://spendmoneyapp.surge.sh/",
    },
  },
  {
    img: urunkatalog,
    isResponsive: false,
    title: "Ürün Katalog Projesi",
    html: true,
    css: true,
    bootstrap: false,
    sass: false,
    js: true,
    jqueryy: false,
    jqueryyui: false,
    tailwindd: true,
    react: true,
    reduxx: true,
    chakra: false,
    node: false,
    mongo: false,
    isCodeBtn: {
      isThere: true,
      link: "https://github.com/alperenkursun/urun-katalog-projesi",
    },
    isSeeBtn: {
      isThere: true,
      link: "https://urunkatalogprojesialperenkursun.surge.sh/",
    },
  },
  {
    img: korfez,
    isResponsive: true,
    title: "Special Security Website",
    html: true,
    css: true,
    bootstrap: false,
    sass: false,
    js: true,
    jqueryy: false,
    jqueryyui: false,
    tailwindd: false,
    react: true,
    reduxx: false,
    chakra: true,
    node: false,
    mongo: false,
    isCodeBtn: {
      isThere: true,
      link: "https://github.com/alperenkursun/special-security-website-project",
    },
    isSeeBtn: {
      isThere: true,
      link: "http://korfezozelguvenlik.surge.sh/",
    },
  },
  {
    img: darkcalculator,
    isResponsive: false,
    title: "Calculator App",
    html: true,
    css: true,
    bootstrap: false,
    sass: false,
    js: true,
    jqueryy: false,
    jqueryyui: false,
    tailwindd: false,
    react: true,
    reduxx: false,
    chakra: false,
    node: false,
    mongo: false,
    isCodeBtn: {
      isThere: true,
      link: "https://github.com/alperenkursun/calculator-app-react",
    },
    isSeeBtn: {
      isThere: true,
      link: "https://calculatorappreact.surge.sh/",
    },
  },
  {
    img: notesapp,
    isResponsive: false,
    title: "Notes App",
    html: true,
    css: true,
    bootstrap: false,
    sass: false,
    js: true,
    jqueryy: false,
    jqueryyui: false,
    tailwindd: false,
    react: true,
    reduxx: true,
    chakra: false,
    node: false,
    mongo: false,
    isCodeBtn: {
      isThere: true,
      link: "https://github.com/alperenkursun/notes-app-redux",
    },
    isSeeBtn: {
      isThere: true,
      link: "https://notesappredux.surge.sh/",
    },
  },
  {
    img: portfolio,
    isResponsive: true,
    title: "Portfolio Project",
    html: true,
    css: true,
    bootstrap: false,
    sass: false,
    js: true,
    jqueryy: false,
    jqueryyui: false,
    tailwindd: false,
    react: true,
    reduxx: false,
    chakra: true,
    node: false,
    mongo: false,
    isCodeBtn: {
      isThere: true,
      link: "https://github.com/alperenkursun/portfolio-project",
    },
    isSeeBtn: {
      isThere: true,
      link: "https://alperenkursun.netlify.app/",
    },
  },
  {
    img: facebookclone,
    isResponsive: false,
    title: "Facebook Clone",
    html: true,
    css: true,
    bootstrap: false,
    sass: false,
    js: true,
    jqueryy: false,
    jqueryyui: false,
    tailwindd: false,
    react: true,
    reduxx: false,
    chakra: true,
    node: false,
    mongo: false,
    isCodeBtn: {
      isThere: true,
      link: "https://github.com/alperenkursun/facebook-clone",
    },
    isSeeBtn: {
      isThere: true,
      link: "https://reactfacebookclone.surge.sh/",
    },
  },
  {
    img: wheather,
    isResponsive: false,
    title: "Wheather App",
    html: true,
    css: true,
    bootstrap: false,
    sass: false,
    js: true,
    jqueryy: false,
    jqueryyui: false,
    tailwindd: false,
    react: true,
    reduxx: false,
    chakra: false,
    node: false,
    mongo: false,
    isCodeBtn: {
      isThere: true,
      link: "https://github.com/alperenkursun/react-weather-app",
    },
    isSeeBtn: {
      isThere: true,
      link: "https://reactwheatherapp.surge.sh/",
    },
  },
  {
    img: reacttodo,
    isResponsive: false,
    title: "Todo Appp",
    html: false,
    css: false,
    bootstrap: false,
    sass: false,
    js: false,
    jqueryy: false,
    jqueryyui: false,
    tailwindd: false,
    react: true,
    reduxx: false,
    chakra: false,
    node: false,
    mongo: false,
    isCodeBtn: {
      isThere: true,
      link: "https://github.com/alperenkursun/react-todo-app",
    },
    isSeeBtn: {
      isThere: true,
      link: "http://reacttodo1app.surge.sh/",
    },
  },
];

export default react_chakra_projects_data;
